name: Auto Scrape and Commit

on:
  schedule:
    # 每天早上6:06 (UTC+8) 执行
    - cron: '6 22 * * *'  # UTC时间22:06 = UTC+8时间06:06
  workflow_dispatch:  # 允许手动触发

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Configure Git
      run: |
        git config --global user.email "${{ secrets.COMMIT_EMAIL }}"
        git config --global user.name "${{ secrets.COMMIT_NAME }}"
        
    - name: Set timezone
      run: |
        sudo timedatectl set-timezone Asia/Shanghai
        
    - name: Run scraping script
      run: |
        cd src
        python app.py
      env:
        TZ: Asia/Shanghai
        
    - name: Commit and push changes
      run: |
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto update: $(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S') UTC+8"
          git push
        fi 